[project]
name = "pygskin"
version = "0.0.1"
dependencies = [
    "pygame-ce",
    "filetype",
    "ruamel.yaml",
]

[tool.isort]
profile = "black"
force_single_line = true
skip_gitignore = true

[tool.flake8]
ignore = "E203"
