[tool.black]
extend-exclude = ""

[tool.ruff]
extend-exclude = []
extend-ignore = ["E203"]
ignore-init-module-imports = true
select = ["E", "F", "I", "B", "C4", "SIM", "N", "FLY", "UP"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = []

[tool.ruff.isort]
force-single-line = true
